import { CELL_W, PEA_DMG } from "./constants";
import type { LevelDef, PlantDef, PlantId, SpawnEvent, ZombieDef, ZombieId } from "./types";

export const PLANTS: Record<PlantId, PlantDef> = {
  sunflower: {
    id: "sunflower",
    name: "日轮花",
    desc: "定时产出阳光。开局优先多种几株，经济才能滚起来。",
    cost: 50,
    recharge: 7.5,
    hp: 300,
    role: "sun",
    night: false,
    range: 0,
    fire: 0,
    dmg: 0,
    sunValue: 25,
    sunEvery: 24,
    sprite: "sunflower",
  },
  peashooter: {
    id: "peashooter",
    name: "青豆炮",
    desc: "本行射击的基础火力。便宜、可靠，用来铺场。",
    cost: 100,
    recharge: 7.5,
    hp: 300,
    role: "shoot",
    night: false,
    range: 9999,
    fire: 1.45,
    dmg: PEA_DMG,
    sprite: "peashooter",
  },
  wallnut: {
    id: "wallnut",
    name: "木盾果",
    desc: "高生命的路障，放在射手前面拖延行尸。",
    cost: 50,
    recharge: 28,
    hp: 4000,
    role: "guard",
    night: false,
    range: 0,
    fire: 0,
    dmg: 0,
    sprite: "wallnut",
  },
  cherry: {
    id: "cherry",
    name: "爆炎果",
    desc: "短暂引信后炸开 3×3 区域，几乎清掉范围内所有行尸。",
    cost: 150,
    recharge: 50,
    hp: 300,
    role: "bomb",
    night: false,
    range: 0,
    fire: 0,
    dmg: 1800,
    splash: "tile3",
    sprite: "cherry",
  },
  snowpea: {
    id: "snowpea",
    name: "霜冻炮",
    desc: "射出寒冰豆，伤害与青豆炮相同，并让目标减速。",
    cost: 175,
    recharge: 7.5,
    hp: 300,
    role: "shoot",
    night: false,
    range: 9999,
    fire: 1.45,
    dmg: PEA_DMG,
    slow: 5.5,
    sprite: "snowpea",
  },
  repeater: {
    id: "repeater",
    name: "连发炮",
    desc: "一次射出两颗豆子，同样的冷却，双倍输出。",
    cost: 200,
    recharge: 7.5,
    hp: 300,
    role: "shoot",
    night: false,
    range: 9999,
    fire: 1.45,
    dmg: PEA_DMG,
    burst: 2,
    sprite: "repeater",
  },
  potato: {
    id: "potato",
    name: "埋爆薯",
    desc: "需要一段时间埋设。就绪后，踩上来的行尸会被炸飞。",
    cost: 25,
    recharge: 28,
    hp: 300,
    role: "mine",
    night: false,
    range: 0,
    fire: 0,
    dmg: 1800,
    armTime: 14,
    sprite: "potato",
  },
  jalapeno: {
    id: "jalapeno",
    name: "炎爆椒",
    desc: "点燃整一行，瞬间烧掉该行所有行尸。",
    cost: 125,
    recharge: 50,
    hp: 300,
    role: "bomb",
    night: false,
    range: 0,
    fire: 0,
    dmg: 1800,
    splash: "row",
    sprite: "jalapeno",
  },
  puffshroom: {
    id: "puffshroom",
    name: "雾喷菇",
    desc: "免费的近距射手。夜间铺场神器，白天会睡着。",
    cost: 0,
    recharge: 7.5,
    hp: 300,
    role: "shoot",
    night: true,
    range: CELL_W * 3.2,
    fire: 1.4,
    dmg: PEA_DMG,
    sprite: "puffshroom",
  },
  sunshroom: {
    id: "sunshroom",
    name: "曦光菇",
    desc: "先产出小阳光，长大后产量与日轮花相同。夜间经济核心。",
    cost: 25,
    recharge: 7.5,
    hp: 300,
    role: "sun",
    night: true,
    range: 0,
    fire: 0,
    dmg: 0,
    sunValue: 15,
    sunEvery: 24,
    sprite: "sunshroom",
  },
  fumeshroom: {
    id: "fumeshroom",
    name: "毒雾菇",
    desc: "喷出穿透毒雾，命中本行前方的所有目标。",
    cost: 75,
    recharge: 7.5,
    hp: 300,
    role: "shoot",
    night: true,
    range: CELL_W * 5.2,
    fire: 1.5,
    dmg: PEA_DMG,
    pierce: true,
    sprite: "fumeshroom",
  },
  scaredyshroom: {
    id: "scaredyshroom",
    name: "怯战菇",
    desc: "远程射手。行尸靠近时会吓得缩起来，停止攻击。",
    cost: 25,
    recharge: 7.5,
    hp: 300,
    role: "shoot",
    night: true,
    range: 9999,
    fire: 1.45,
    dmg: PEA_DMG,
    sprite: "scaredyshroom",
  },
};

export const PLANT_ORDER: PlantId[] = [
  "sunflower",
  "peashooter",
  "wallnut",
  "cherry",
  "potato",
  "snowpea",
  "repeater",
  "jalapeno",
  "puffshroom",
  "sunshroom",
  "fumeshroom",
  "scaredyshroom",
];

export const ZOMBIES: Record<ZombieId, ZombieDef> = {
  basic: {
    id: "basic",
    name: "园丁尸",
    desc: "普通的行尸，缓慢而执着。一排青豆炮就能对付。",
    hp: 200,
    armor: 0,
    armorKind: "none",
    speed: 24,
    eat: 100,
  },
  cone: {
    id: "cone",
    name: "路障尸",
    desc: "头上扣着路障，血量约为普通行尸的三倍。",
    hp: 200,
    armor: 370,
    armorKind: "cone",
    speed: 24,
    eat: 100,
    spriteAcc: "cone",
  },
  bucket: {
    id: "bucket",
    name: "铁桶尸",
    desc: "铁桶极为抗打，需要集火或爆炸植物。",
    hp: 200,
    armor: 1100,
    armorKind: "bucket",
    speed: 24,
    eat: 100,
    spriteAcc: "bucket",
  },
  flag: {
    id: "flag",
    name: "旗手尸",
    desc: "一波进攻的信号。比普通行尸稍快一点。",
    hp: 200,
    armor: 0,
    armorKind: "none",
    speed: 30,
    eat: 100,
    spriteAcc: "flag",
  },
  newspaper: {
    id: "newspaper",
    name: "读报尸",
    desc: "护着一份旧报纸。报纸被打烂后会暴怒冲刺。",
    hp: 200,
    armor: 150,
    armorKind: "paper",
    speed: 22,
    eat: 100,
    spriteAcc: "newspaper",
  },
  football: {
    id: "football",
    name: "橄榄尸",
    desc: "又快又厚的冲锋手。尽快用坚果和爆炸拖住它。",
    hp: 1400,
    armor: 0,
    armorKind: "helmet",
    speed: 48,
    eat: 140,
    spriteAcc: "helmet",
  },
  pole: {
    id: "pole",
    name: "撑杆尸",
    desc: "跑得很快，会撑杆跳过它遇到的第一株植物。",
    hp: 500,
    armor: 0,
    armorKind: "none",
    speed: 52,
    eat: 100,
    spriteAcc: "pole",
  },
  door: {
    id: "door",
    name: "铁门尸",
    desc: "举着铁门当盾。毒雾可以越过盾牌直接伤身。",
    hp: 200,
    armor: 1100,
    armorKind: "door",
    speed: 22,
    eat: 100,
    spriteAcc: "door",
  },
};

export const ZOMBIE_ORDER: ZombieId[] = [
  "basic",
  "cone",
  "bucket",
  "flag",
  "newspaper",
  "football",
  "pole",
  "door",
];

type Wave = {
  t: number;
  flag?: boolean;
  huge?: boolean;
  g: Array<[ZombieId, number, number]>;
};

function compile(waves: Wave[]): SpawnEvent[] {
  const out: SpawnEvent[] = [];
  for (const w of waves) {
    if (w.flag) out.push({ t: w.t, type: "flag", row: -1, flag: true, huge: w.huge });
    let t = w.t + (w.flag ? 0.5 : 0);
    for (const [type, n, gap] of w.g) {
      for (let i = 0; i < n; i++) {
        out.push({ t, type, row: -1, huge: w.huge });
        t += gap;
      }
    }
  }
  out.sort((a, b) => a.t - b.t);
  return out;
}

export const LEVELS: LevelDef[] = [
  {
    id: "1-1",
    name: "初入前院",
    chapter: "阳光前院",
    theme: "day",
    startSun: 250,
    flags: 1,
    graves: 0,
    forced: ["peashooter"],
    advice: ["peashooter"],
    reward: "sunflower",
    note: "点选种子，点在草地上种植。点掉落的阳光才能收集。",
    spawns: compile([
      { t: 32, g: [["basic", 1, 0]] },
      { t: 54, g: [["basic", 1, 0]] },
      { t: 78, g: [["basic", 2, 8]] },
      { t: 108, flag: true, g: [["basic", 4, 3.6]] },
    ]),
  },
  {
    id: "1-2",
    name: "阳光计划",
    chapter: "阳光前院",
    theme: "day",
    startSun: 50,
    flags: 1,
    graves: 0,
    forced: ["sunflower", "peashooter"],
    advice: ["sunflower", "peashooter"],
    reward: "cherry",
    note: "先种日轮花，等阳光再铺射手。",
    spawns: compile([
      { t: 36, g: [["basic", 1, 0]] },
      { t: 60, g: [["basic", 1, 0]] },
      { t: 84, g: [["basic", 2, 7]] },
      { t: 122, flag: true, g: [["basic", 5, 3.2]] },
    ]),
  },
  {
    id: "1-3",
    name: "爆裂樱桃",
    chapter: "阳光前院",
    theme: "day",
    startSun: 50,
    flags: 1,
    graves: 0,
    advice: ["sunflower", "peashooter", "cherry"],
    reward: "wallnut",
    note: "爆炎果能瞬间清掉挤成一团的行尸。",
    spawns: compile([
      { t: 30, g: [["basic", 1, 0]] },
      { t: 52, g: [["basic", 2, 6]] },
      { t: 78, g: [["basic", 3, 4], ["cone", 1, 5]] },
      { t: 112, flag: true, g: [["basic", 6, 2.6], ["cone", 1, 3.5]] },
    ]),
  },
  {
    id: "1-4",
    name: "坚果防线",
    chapter: "阳光前院",
    theme: "day",
    startSun: 50,
    flags: 2,
    graves: 0,
    advice: ["sunflower", "peashooter", "wallnut", "cherry"],
    reward: "potato",
    note: "把木盾果放在射手前面，给输出争取时间。",
    spawns: compile([
      { t: 28, g: [["basic", 2, 6]] },
      { t: 54, g: [["basic", 2, 4], ["cone", 1, 5]] },
      { t: 86, flag: true, g: [["basic", 4, 2.8], ["cone", 2, 3.2]] },
      { t: 124, g: [["basic", 3, 3.2], ["cone", 2, 3.5]] },
      { t: 162, flag: true, g: [["basic", 7, 2.2], ["cone", 3, 2.8]] },
    ]),
  },
  {
    id: "1-5",
    name: "埋藏的惊喜",
    chapter: "阳光前院",
    theme: "day",
    startSun: 50,
    flags: 2,
    graves: 0,
    advice: ["sunflower", "peashooter", "wallnut", "potato", "cherry"],
    reward: "snowpea",
    note: "埋爆薯需要时间就绪，提前埋在前排。",
    spawns: compile([
      { t: 24, g: [["basic", 2, 5]] },
      { t: 50, g: [["cone", 2, 4], ["basic", 2, 3]] },
      { t: 78, flag: true, g: [["basic", 6, 1.6], ["cone", 2, 2.4]] },
      { t: 114, g: [["basic", 4, 2], ["cone", 3, 2.6]] },
      { t: 152, flag: true, huge: true, g: [["basic", 10, 1.1], ["cone", 4, 1.6]] },
    ]),
  },
  {
    id: "1-6",
    name: "寒霜来临",
    chapter: "阳光前院",
    theme: "day",
    startSun: 50,
    flags: 2,
    graves: 0,
    advice: ["sunflower", "peashooter", "snowpea", "wallnut", "cherry"],
    reward: "repeater",
    note: "霜冻炮减速铁桶尸，给火力窗口。",
    spawns: compile([
      { t: 24, g: [["basic", 2, 4]] },
      { t: 48, g: [["cone", 2, 3], ["basic", 2, 2.5]] },
      { t: 72, g: [["bucket", 1, 0], ["cone", 2, 3]] },
      { t: 96, flag: true, g: [["basic", 6, 1.5], ["cone", 3, 2], ["bucket", 1, 0]] },
      { t: 132, g: [["cone", 3, 2.2], ["bucket", 2, 4]] },
      { t: 170, flag: true, g: [["basic", 8, 1.2], ["cone", 4, 1.6], ["bucket", 2, 2.8]] },
    ]),
  },
  {
    id: "1-7",
    name: "火力加倍",
    chapter: "阳光前院",
    theme: "day",
    startSun: 50,
    flags: 2,
    graves: 0,
    advice: ["sunflower", "repeater", "snowpea", "wallnut", "cherry"],
    reward: "jalapeno",
    note: "连发炮是中后期的主力输出。",
    spawns: compile([
      { t: 22, g: [["basic", 3, 3]] },
      { t: 48, g: [["cone", 3, 2.4], ["basic", 2, 2]] },
      { t: 72, g: [["bucket", 2, 4], ["cone", 2, 2.2]] },
      { t: 98, flag: true, g: [["basic", 6, 1.3], ["cone", 3, 1.8], ["bucket", 2, 2.6]] },
      { t: 136, g: [["bucket", 2, 2.8], ["cone", 4, 1.8]] },
      { t: 172, flag: true, huge: true, g: [["basic", 10, 0.9], ["cone", 5, 1.3], ["bucket", 3, 2]] },
    ]),
  },
  {
    id: "1-8",
    name: "焦土清场",
    chapter: "阳光前院",
    theme: "day",
    startSun: 50,
    flags: 2,
    graves: 0,
    advice: ["sunflower", "repeater", "snowpea", "wallnut", "jalapeno", "cherry"],
    reward: "puffshroom",
    note: "炎爆椒清一整行。读报尸丢了报纸会狂奔。",
    spawns: compile([
      { t: 22, g: [["basic", 2, 3.5]] },
      { t: 46, g: [["newspaper", 2, 5], ["cone", 2, 3]] },
      { t: 72, g: [["bucket", 2, 4], ["newspaper", 1, 3]] },
      { t: 98, flag: true, g: [["basic", 5, 1.4], ["cone", 3, 2], ["newspaper", 2, 2.4], ["bucket", 1, 0]] },
      { t: 136, g: [["newspaper", 3, 2.2], ["bucket", 2, 2.8], ["cone", 3, 2]] },
      { t: 172, flag: true, huge: true, g: [["basic", 8, 0.9], ["newspaper", 4, 1.4], ["cone", 4, 1.3], ["bucket", 3, 1.8]] },
    ]),
  },
  {
    id: "2-1",
    name: "黑夜初临",
    chapter: "月光后院",
    theme: "night",
    startSun: 50,
    flags: 1,
    graves: 3,
    advice: ["puffshroom", "sunflower", "peashooter", "wallnut"],
    reward: "sunshroom",
    note: "夜里没有天上掉落的阳光。免费雾喷菇先铺满前排。",
    spawns: compile([
      { t: 22, g: [["basic", 2, 4]] },
      { t: 40, g: [["basic", 4, 2.2]] },
      { t: 62, g: [["cone", 2, 3], ["basic", 3, 1.8]] },
      { t: 88, flag: true, g: [["basic", 8, 1.1], ["cone", 3, 1.6]] },
    ]),
  },
  {
    id: "2-2",
    name: "微光蘑菇",
    chapter: "月光后院",
    theme: "night",
    startSun: 25,
    flags: 2,
    graves: 4,
    advice: ["sunshroom", "puffshroom", "peashooter", "wallnut", "cherry"],
    reward: "fumeshroom",
    note: "曦光菇是夜间的经济。长大后产量更高。",
    spawns: compile([
      { t: 20, g: [["basic", 3, 2.5]] },
      { t: 42, g: [["cone", 2, 2.4], ["basic", 3, 1.8]] },
      { t: 66, flag: true, g: [["basic", 6, 1.1], ["cone", 3, 1.5], ["newspaper", 1, 0]] },
      { t: 98, g: [["cone", 4, 1.6], ["bucket", 1, 0], ["basic", 4, 1.4]] },
      { t: 130, flag: true, g: [["basic", 9, 0.9], ["cone", 4, 1.2], ["newspaper", 3, 1.6], ["bucket", 2, 2]] },
    ]),
  },
  {
    id: "2-3",
    name: "毒雾弥漫",
    chapter: "月光后院",
    theme: "night",
    startSun: 25,
    flags: 2,
    graves: 5,
    advice: ["sunshroom", "puffshroom", "fumeshroom", "wallnut", "jalapeno"],
    reward: "scaredyshroom",
    note: "毒雾菇能打穿铁门。铁门尸出现了。",
    spawns: compile([
      { t: 18, g: [["basic", 3, 2.2]] },
      { t: 40, g: [["door", 2, 4], ["cone", 2, 2]] },
      { t: 64, g: [["newspaper", 3, 2], ["bucket", 1, 0]] },
      { t: 86, flag: true, g: [["basic", 6, 1], ["door", 3, 1.8], ["cone", 3, 1.3]] },
      { t: 120, g: [["door", 3, 2], ["bucket", 2, 2.4], ["newspaper", 3, 1.6]] },
      { t: 154, flag: true, huge: true, g: [["basic", 8, 0.7], ["door", 4, 1.2], ["cone", 5, 1], ["bucket", 3, 1.6]] },
    ]),
  },
  {
    id: "2-4",
    name: "月下总攻",
    chapter: "月光后院",
    theme: "night",
    startSun: 50,
    flags: 3,
    graves: 6,
    advice: ["sunshroom", "fumeshroom", "scaredyshroom", "wallnut", "jalapeno", "cherry", "snowpea"],
    note: "撑杆尸会跳过第一株植物。橄榄尸又快又肉。守住这一夜。",
    spawns: compile([
      { t: 16, g: [["basic", 3, 2]] },
      { t: 34, g: [["pole", 2, 3], ["cone", 2, 2]] },
      { t: 54, g: [["football", 1, 0], ["door", 2, 3]] },
      { t: 74, flag: true, g: [["basic", 6, 0.9], ["pole", 3, 1.5], ["cone", 3, 1.2]] },
      { t: 108, g: [["football", 2, 4], ["newspaper", 3, 1.8], ["bucket", 2, 2]] },
      { t: 138, flag: true, g: [["pole", 4, 1.2], ["door", 3, 1.6], ["cone", 4, 1], ["football", 1, 0]] },
      { t: 168, g: [["bucket", 3, 1.8], ["newspaper", 4, 1.4], ["pole", 3, 1.6]] },
      { t: 198, flag: true, huge: true, g: [["basic", 10, 0.55], ["football", 3, 1.8], ["pole", 4, 1], ["door", 3, 1.3], ["bucket", 3, 1.4], ["cone", 5, 0.8]] },
    ]),
  },
];

export function survivalWave(n: number): SpawnEvent[] {
  const t0 = 14;
  const count = 5 + n * 2;
  const gap = Math.max(0.45, 1.35 - n * 0.06);
  const bag: ZombieId[] = ["basic", "basic", "basic", "cone"];
  if (n >= 2) bag.push("cone", "newspaper");
  if (n >= 3) bag.push("bucket", "door");
  if (n >= 4) bag.push("pole");
  if (n >= 5) bag.push("football", "bucket");
  if (n >= 7) bag.push("football", "pole", "door");
  const g: Array<[ZombieId, number, number]> = [];
  const types: Record<string, number> = {};
  for (let i = 0; i < count; i++) {
    const id = bag[i % bag.length]!;
    types[id] = (types[id] ?? 0) + 1;
  }
  for (const [id, c] of Object.entries(types)) {
    g.push([id as ZombieId, c, gap]);
  }
  return compile([{ t: t0, flag: n % 2 === 0, huge: n > 0 && n % 3 === 0, g }]);
}

export const SURVIVAL: LevelDef = {
  id: "survival",
  name: "无尽生存",
  chapter: "试炼",
  theme: "day",
  startSun: 150,
  flags: 99,
  graves: 0,
  advice: PLANT_ORDER,
  note: "波次会不断加强。能守住多少波？",
  spawns: survivalWave(0),
};
